### ISSUE TITLE
[Question] Privacy model and some technical explorations

### ISSUE THREAD

**Issue by 0xtsukino** [InterRep/contracts#5]
Hey Raphael - thank you for making InterRep, really cool project!

I am exploring possibilities for building a pseudonymous social network, and I have some questions about InterRep.

### Privacy Model
I am trying to understand the what kind of trust I am placing on the verification service. It seems that I must associate a twitter handle with an ETH address, but there is also an ecryption flow that seems to suggest that I don't have to trust the service with the association. Given that *eventually* the relationship must be revealed on-chain in order to mint the badge, I am trying to understand what the encryption does.

To be clear though, I don't think of it as a problem either way. I think there exists a need for "reputation mixer" where similar profiles can form an anonymity set and attest a ZK proofs about inclusion in such set. For example, an NFT that represents the holder has "25k Twitter Followers" or "2k Github stars" would be a new way to build up a new pseud.

### Encryption

> The signature, the message (together forming an attestation) and a salt is encrypted with the user's public key. The link between a Twitter account and an address is neither logged nor saved anywhere other than in the encrypted attestation. This means that only the user, with their private key, has the ability to reveal this association.

Is the public key the same as my ETH address? If so, that means once I revealed, everyone will know about the association on-chain, correct?

### On-Chain Reputation
Is there any plans to put more detailed stats on-chain? For example, I am thinking that reputation such as follower counts/github stars would be super useful, but I feel like we msut use an off-chain oracle for this, as putting these data on-chain requires periodic push and costs lot of gas.

Look forward to your response :)

**Comment by ra-phael** [comment]
Hi @0xtsukino, thank you for your questions!

InterRep started from the assumption that we needed a centralized server anyway to perform OAuth (though we would like to decentralize it); that might be the missing piece in your understanding of the service?
The association is never revealed on-chain. The NFT that gets minted has just a unique id and represents a reputable Twitter account, but from that alone you cannot determine which Twitter account.

There are 2 challenges that we faced:
1. Preventing someone from minting more than 1 NFT from the same Twitter account
For that you first have to link your account with your ethereum address: the account is marked as linked in our database, making it impossible to mint another NFT for that account.

2. Allowing users to change the association, i.e switching the address that is linked to your Twitter account while maintaining privacy
In order to do that, we do store the association in the database, not on-chain, but that's where the encryption comes in. 
The association first gets encrypted with the users' ethereum public key (from which the address is derived) before being stored, such that only they can decrypt it with their private key. Although I have access to the database there's no way for me to reveal any association. 
You only need to reveal the association if you want to "unlink": you first decrypt the association on the front-end which then gets passed to the server decrypted so there's a brief moment where it's revealed. ZKP would alleviate that.

One other important point about the trust model is that InterRep has the ability to mint badges / NFTs but not to revoke them.

### More granular reputation signals

> Is there any plans to put more detailed stats on-chain?

When we started InterRep we had this goal in mind to do "sybil-resistance-as-a-service". So just knowing that an address is verified by InterRep is enough but you're absolutely right that it would be really cool to have more detailed information on-chain. Although one has to be mindful about cross-checking several data points (like a specific number of followers) which could doxx you. I think someone should be able to prove that they have more than X number of followers or stars using ZKP. And yes getting that kind of data seems like a good fit for an oracle.

I hope that answers your questions! :)
